# Generated by Django 3.2.5 on 2025-03-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDLETNewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=400)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('snippet', models.CharField(blank=True, max_length=400)),
                ('domain', models.URLField(blank=True)),
                ('socialimage', models.ImageField(blank=True, upload_to='media/')),
                ('language', models.CharField(max_length=250)),
                ('seendate', models.DateField()),
            ],
        ),
    ]
