# Generated by Django 3.2.5 on 2025-03-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20250323_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdletnewsmodel',
            name='seendate',
            field=models.DateTimeField(),
        ),
    ]
