# Generated by Django 3.2.5 on 2025-03-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0004_auto_20250323_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdletnewsmodel',
            name='sentiment_analysis',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
