# Generated by Django 3.2.5 on 2025-03-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_gdletnewsmodel_sentiment_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdletnewsmodel',
            name='sentiment_analysis',
        ),
    ]
