# Generated by Django 3.2.5 on 2025-03-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_remove_gdletnewsmodel_sentiment_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdletnewsmodel',
            name='socialimage',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
