# Generated by Django 3.2.5 on 2025-03-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0007_alter_gdletnewsmodel_socialimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdletnewsmodel',
            name='socialimage',
            field=models.URLField(blank=True),
        ),
    ]
