# Generated by Django 3.2.5 on 2025-03-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0008_alter_gdletnewsmodel_socialimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdletnewsmodel',
            name='sentiment_analysis',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
